version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./developer-env/postgres/:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data